# Generated by Django 2.2.1 on 2020-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='books_authors_events',
            field=models.BooleanField(db_column='BooksAuthorsEvents', default=False, help_text='books_authors_events'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='new_offers',
            field=models.BooleanField(db_column='NewOffers', default=False, help_text='new_offers'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='recommendations',
            field=models.BooleanField(db_column='Recommendations', default=True, help_text='Recommendations'),
        ),
    ]
