# Generated by Django 2.2.1 on 2019-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, help_text='A short review about user.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kind_books',
            field=models.TextField(blank=True, help_text="User's book subject preferences."),
        ),
    ]
