# Generated by Django 2.2.1 on 2019-05-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190528_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelve',
            name='user',
        ),
        migrations.AddField(
            model_name='shelve',
            name='owner',
            field=models.ForeignKey(default=1, help_text="Shelve' owner.", on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookshelve',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='bookshelve',
            name='shelve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.Shelve'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_view',
            field=models.CharField(choices=[('1', 'Age & birthday to Goodreads members'), ('2', 'Age to Goodreads members, birthday to friends'), ('3', 'Age to Goodreads members, birthday to no one'), ('4', 'Age and birthday to friends'), ('5', 'Age to friends, birthday to no one'), ('6', 'Age and birthday to no one'), ('7', 'Age to no one, birthday to Goodreads members'), ('8', 'Age to no one, birthday to friends')], help_text="Who can see user's age and birthday.", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
