# Generated by Django 2.2.1 on 2019-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190529_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True, db_column='Photo', help_text="User's profile image."),
        ),
    ]
