# Generated by Django 2.2.1 on 2019-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190529_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, db_column='Photo', help_text="User's profile image.", upload_to=''),
        ),
    ]
