# Generated by Django 2.2.1 on 2019-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190529_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_view',
            field=models.CharField(choices=[('1', 'Age & birthday to Goodreads members'), ('2', 'Age to Goodreads members, birthday to friends'), ('3', 'Age to Goodreads members, birthday to no one'), ('4', 'Age and birthday to friends'), ('5', 'Age to friends, birthday to no one'), ('6', 'Age and birthday to no one'), ('7', 'Age to no one, birthday to Goodreads members'), ('8', 'Age to no one, birthday to friends')], default='2', help_text="Who can see user's age and birthday.", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, db_column='Birthday', help_text="User's birthday."),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('X', 'X')], help_text="User's gender.", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_view',
            field=models.CharField(choices=[('F', 'Friends only'), ('E', 'Everyone'), ('N', 'No one')], default='F', help_text="Who can see user's gender", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_view',
            field=models.CharField(choices=[('F', 'Friends only'), ('E', 'Everyone'), ('N', 'No one')], default='E', help_text="Who can see user's location.", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='who_can_see_last_name',
            field=models.CharField(choices=[('F', 'Friends only'), ('E', 'Everyone'), ('N', 'No one')], default='F', max_length=2),
        ),
    ]
