# Generated by Django 2.2.1 on 2019-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190529_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, db_column='Birthday', help_text="User's birthday.", null=True),
        ),
    ]
