# Generated by Django 2.2.1 on 2019-06-11 13:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_feedsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelve',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='bookshelve',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='favoritegenre',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='favoritegenre',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='feedsetting',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='feedsetting',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='groupemailsetting',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='groupemailsetting',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='description',
            field=models.TextField(db_column='Description', default='hola description', help_text='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='privacy',
            field=models.CharField(choices=[('PU', 'Public'), ('R', 'Restricted'), ('PR', 'Private'), ('S', 'Secret')], default='PU', help_text='this group is', max_length=2),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='rules',
            field=models.TextField(blank=True, db_column='Rules', help_text='Rules'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='show_rules_only_new_members',
            field=models.BooleanField(db_column='ShowRulesOnlyNewMembers', default=True, help_text='Show rules only to new members'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='subtopic',
            field=models.CharField(blank=True, db_column='subtopic', help_text='Subtopic', max_length=3),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='tags',
            field=models.TextField(db_column='Tags', default='tag', help_text='Tags'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='topic',
            field=models.CharField(choices=[('BL', 'Books & Literature'), ('B', 'Business'), ('EA', 'Entertainment & Art'), ('FC', 'Friends & Commons Interests'), ('G', 'Geography'), ('GA', 'Goodreads authors'), ('JF', 'Just for fun'), ('O', 'Organizations'), ('SG', 'Students groups')], db_column='Topic', default='AF', help_text='Group or bookclub topic', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelve',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='shelve',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
