# Generated by Django 2.2.1 on 2019-06-11 13:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190611_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='challenge_question',
            field=models.TextField(blank=True, db_column='ChallengeQuestion', help_text='Challenge question, only for private groups'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='country',
            field=django_countries.fields.CountryField(db_column='Country', default='AU', help_text='country', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='display_video_top',
            field=models.BooleanField(db_column='DisplayVideo', default=False, help_text="Display videos at the top of this group's homepage"),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='group_email_setting',
            field=models.CharField(choices=[('D', 'Digest'), ('I', 'Individual'), ('A', 'All'), ('O', 'Notification only'), ('N', 'None')], db_column='GroupEmailSett', default='D', help_text='Group discussion email settings', max_length=2),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='meet_real_life',
            field=models.BooleanField(db_column='MeetRealLife', default=False, help_text='This group meets in real life'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='mod_post_highlighted',
            field=models.BooleanField(db_column='ModeratorPostHighlighted', default=True, help_text='Moderator posts are highlighted'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='non_mod_add_book',
            field=models.BooleanField(db_column='NonModeratorAddBook', default=True, help_text="Non-moderator can add books to this group's shelf"),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='non_mod_add_event',
            field=models.BooleanField(db_column='NonModeratorAddEvent', default=True, help_text='Non-moderator can add events'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='only_adults',
            field=models.BooleanField(db_column='OnlyAdults', default=False, help_text='For adults only'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='postal_code',
            field=models.CharField(blank=True, db_column='PostalCode', help_text='Postal code(for local group)', max_length=25),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='website',
            field=models.CharField(blank=True, db_column='WebSite', help_text='Affiliated website', max_length=150),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='privacy',
            field=models.CharField(choices=[('PU', 'Public'), ('R', 'Restricted'), ('PR', 'Private'), ('S', 'Secret')], db_column='Privacy', default='PU', help_text='this group is', max_length=2),
        ),
    ]
