# Generated by Django 2.2.1 on 2019-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('AU', 'Author'), ('IL', 'Illustrator'), ('CO', 'Contributor'), ('ED', 'Editor'), ('TR', 'Translator'), ('NA', 'Narrator')], default='AU', help_text='', max_length=2, null=True),
        ),
    ]
