# Generated by Django 2.2.1 on 2019-06-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text="Book's title.", max_length=150),
        ),
        migrations.AlterModelTable(
            name='bookreview',
            table='BookReview',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Genre'),
            preserve_default=False,
        ),
    ]
