"""
Django settings for goodreads project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$qbaqg^yg&ug_(!wp@n&5xbv@^#r$z-#y31waylk(8k0md1c+k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'languages',
    'apps.accounts',
    'apps.books',
    'django_countries',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'goodreads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goodreads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.UserProfile'


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    # When you enable API versioning, the request.version attribute will contain a string
    # that corresponds to the version requested in the incoming client request.
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer', 'Goodreads')
}

# Email values
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'adrianminfo90@gmail.com'
EMAIL_HOST_PASSWORD = 'hijadelafortuna*'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'adrianminfo90@gmail.com'
SERVER_EMAIL = 'adrianminfo90@gmail.com'
# EMAIL_USE_SSL = True

# Constants
GENDER = (('F', _('Female')), ('M', _('Male')), ('X', 'X'))
PERMISSION_VIEW = (('F', _('Friends only')), ('E', _('Everyone')), ('N', _('No one')))
AGE_BIRTHDAY_PRIVACY = (
    ('1', _('Age & birthday to Goodreads members')),
    ('2', _('Age to Goodreads members, birthday to friends')),
    ('3', _('Age to Goodreads members, birthday to no one')),
    ('4', _('Age and birthday to friends')),
    ('5', _('Age to friends, birthday to no one')),
    ('6', _('Age and birthday to no one')),
    ('7', _('Age to no one, birthday to Goodreads members')),
    ('8', _('Age to no one, birthday to friends'))
)
PROFILE_PERMISSIONS_VIEW = (('A', _('Anyone(including search engines)')), ('G', _('Goodreads members')),
                            ('F', 'Just my friends'))
EMAIL_FREQUENCY = (('N', _('Never')), ('D', _('Once a day')), ('W', _('Once a week')))
COMMENT_NOTIFICATION = (('E', _('an email')), ('N', _('a notification')), ('B', _('both')), ('A', _('Nothing')))
DISCUSSION_EMAIL_FREQUENCY = (('D', _('Daily')), ('W', _('Weekly')))
GROUP_GET_EMAIL_FREQUENCY = (('D', _('Digest')), ('I', _('Individual')), ('A', _('All')), ('O', _('Notification only')),
                             ('N', _('None')))
GROUP_TOPIC = (('BL', _('Books & Literature')), ('B', _('Business')), ('EA', _('Entertainment & Art')),
               ('FC', _('Friends & Commons Interests')), ('G', _('Geography')), ('GA', _('Goodreads authors')),
               ('JF', _('Just for fun')), ('O', _('Organizations')), ('SG', _('Students groups')))
GROUP_SUBTOPIC = {
    'BL': (
        ('AF', _('Arts & Photography')), ('BM', _('Biographies & Memoirs')), ('BI', _('Business & Investing')),
        ('ChB', _('Children\'s books')), ('CGN', _('Comics & Graphic Novels')), ('CI', _('Computers & Internet')),
        ('CFW', _('Cooking, Food & Wine')), ('E', _('Entertainment')), ('GL', _('Gay & Lesbian')),
        ('G',_('General')), ('HMB', _('Health, Mind & Body')), ('H', _('History')), ('HG', _('Home & Garden')),
        ('HO', _('Horror')), ('LF', _('LIterature & Fiction')), ('MT', _('Mystery & Thrillers')),
        ('NF', _('Nonfiction')), ('ON', _('Outdoors & Nature')), ('P', _('Parenting & Family')),
        ('PO', _('Poetry')), ('PT', _('Professional & Technical')), ('RF', _('Reference')),
        ('RS', _('Religion & Spirituality')), ('RO', _('Romance')), ('S', _('Science')),
        ('SCF', _('Science Fiction & Fantansy')), ('SP', _('Sports')), ('TR', _('Travels')), ('YA', _('Young Adults'))
    ),
    'B': (
        ('C', _('Companies')), ('CG', _('Consumer Groups')), ('EW', _('Employment & Work')), ('G', _('General')),
        ('HB', _('Home business')), ('IT', _('Internet & Technology')), ('I', _('Investing')),
        ('MA', _('Marketing & Advertising')), ('PR', _('Public Realtions')), ('RE', _('Real Estate'))
    ),
    'EA': (
        ('C', _('Celebrities')), ('CA', _('Comics & Animation')), ('D', _('Dance')), ('F', _('Fashion'))
    ),
    'FC': (
        ('A', _('Activities'))
    ),
    'G': (
        ('C', _('Countries'))
    ),
    'GA': (
        ('AF', _('Arts & Photography')), ('BM', _('Biographies & Memoirs')), ('BI', _('Business & Investing')),
        ('ChB', _('Children\'s books')), ('CGN', _('Comics & Graphic Novels')), ('CI', _('Computers & Internet')),
        ('CFW', _('Cooking, Food & Wine')), ('E', _('Entertainment')), ('GL', _('Gay & Lesbian')),
        ('G',_('General')), ('HMB', _('Health, Mind & Body')), ('H', _('History')), ('HG', _('Home & Garden')),
        ('HO', _('Horror')), ('LF', _('LIterature & Fiction')), ('MT', _('Mystery & Thrillers')),
        ('NF', _('Nonfiction')), ('ON', _('Outdoors & Nature')), ('P', _('Parenting & Family')),
        ('PO', _('Poetry')), ('PT', _('Professional & Technical')), ('RF', _('Reference')),
        ('RS', _('Religion & Spirituality')), ('RO', _('Romance')), ('S', _('Science')),
        ('SCF', _('Science Fiction & Fantansy')), ('SP', _('Sports')), ('TR', _('Travels')), ('YA', _('Young Adults'))
    ),
    'JF': (
        ('FC', _('Fan Clubs'))
    ),
    'O': (
        ('AO', _('Academic Organizations'))
    ),
    'SG': (
        ('AG', _('Academic Groups'))
    )
}

GROUP_PRIVACY = (('PU', _('Public')), ('R', _('Restricted')), ('PR', _('Private')), ('S', _('Secret')))

AUTHOR_ROLE = (('AU', _('Author')), ('IL', _('Illustrator')), ('CO', _('Contributor')), ('ED', _('Editor')),
               ('TR', _('Translator')), ('NA', _('Narrator')))

BOOK_FORMAT = (('PB', _('Paperback')), ('HC', _('Hardcover')), ('KE', _('Kindle Edition')),
               ('MMP', _('Mass Market paperback')), ('N', _('Nook')), ('E', _('ebook')), ('LB', _('Library Binding')),
               ('AB', _('Audiobook')), ('AC', _('Audio CD')), ('ACA', _('Audio Cassette')), ('AA', _('Audible Audio')),
               ('CD', _('CD-ROM')), ('MP3', _('MP3 CD')), ('BB', _('Board book')), ('LB', _('Leather bound')),
               ('UN', _('Unbound')), ('SB', _('Spiral-bound')), ('UB', _('Unkown bingind')))

MEDIA_TYPE = (('B', _('Book')), ('P', _('Periodical')), ('A', _('Article')), ('NB', _('Not a book')))
BOOK_GENRE = (('M', _('Mystery')), ('C', _('Comedy')), ('F', _('Fiction')), ('Ch', _('Childrens')),
              ('A', _('Adventure')), ('R', _('Romance')), ('Ft', _('Fairytale')), ('Th', _('Thriller')),
              ('Nf', _('Nonfiction')), ('Ws', _('Women\'s studies')), ('Ma', _('Middle age')),
              ('Mag', _('Young adult')), ('Me', _('Medieval')), ('Fa', _('Multiverse')))
BOOK_SUBJECTS = (('W', _('War')), ('F', _('Friendship')), ('R', _('Relationships')), ('Re', _('Responsibility')),
                 ('O', _('Optimism')), ('H', _('Hope')), ('TGO', _('Triumph of good over evil')), ('Fa', _('Fantansy')),
                 ('Wi', _('Wizard')), ('I', _('Infiltrations')), ('M', _('Murders')), ('Wit', _('Witches')),
                 ('P', _('Psychology')), ('Inf', _('Infiltrations')), ('Fd', _('Fire demons')))

BOOK_PACE = (('Fp', _('Fast paced')), ('Rp', _('Relaxed-pace')))
BOOK_TONE = (('H', _('Humor')), ('R', _('Romance')), ('M', _('Mysterious')), ('F', _('Fantasy')), ('A', _('Academic')))
WRITING_STYLE = (('D', _('Descriptive')), ('W', _('Whimsical')), ('Sp', _('Slightly proper')),
                 ('AiC', _('As it comes')), ('B', _('Brilliant')))
NARRATION_PERSPECTIVE = (('3rd', _('3rd person')), ('1st', _('1st person')), ('2nd', _('2dn person')),
                         ('S', _('Shifting perspectives')))
BOOK_TIME = (('Pr', _('Present')), ('Pa', _('Past')), ('S', _('Shifting')))
SHORT_ANSWER = (('Y', _('Yes')), ('N', _('No')))
CHARACTERS_AMOUNT = (('F', _('Few')), ('M', _('Many')))

TEST_IMAGE_PATH = os.path.join(BASE_DIR, 'static/test/test_image.png')
